// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGErydPJ88ppotpF2-1RaYOfTo1rlUwgc',
    appId: '1:137833612938:web:5239e549dcc5c783220f73',
    messagingSenderId: '137833612938',
    projectId: 'samaeer-d8105',
    authDomain: 'samaeer-d8105.firebaseapp.com',
    storageBucket: 'samaeer-d8105.appspot.com',
    measurementId: 'G-VYVLC79YP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fMoVPRGw-9dyFu5dMGn1JZYfGWrXAp4',
    appId: '1:137833612938:android:0a3b598d2cee5f82220f73',
    messagingSenderId: '137833612938',
    projectId: 'samaeer-d8105',
    storageBucket: 'samaeer-d8105.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsYd19oCwjOVWcmXnNn2ZSRVvy6uOWD_s',
    appId: '1:137833612938:ios:f03be4f430a0c1b9220f73',
    messagingSenderId: '137833612938',
    projectId: 'samaeer-d8105',
    storageBucket: 'samaeer-d8105.appspot.com',
    iosClientId:
        '137833612938-nhqa660jbvnvfrqvha33loqlim31v7te.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsYd19oCwjOVWcmXnNn2ZSRVvy6uOWD_s',
    appId: '1:137833612938:ios:bdeb8a0fc831b238220f73',
    messagingSenderId: '137833612938',
    projectId: 'samaeer-d8105',
    storageBucket: 'samaeer-d8105.appspot.com',
    iosClientId:
        '137833612938-gc7dpco7s02372bnno1gpnnqm9lh4jmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProj.RunnerTests',
  );
}
